# Input topics handled/muxed.
# For each topic:
# - name    : name identifier to select the topic
# - topic   : input topic of geometry_msgs::Twist type
# - timeout : timeout in seconds to start discarding old messages, and use 0.0 speed instead
# - priority: priority in the range [0, 255]; the higher the more priority over other topics

topics:
-
  name    : navigation # velocity from navigation planner
  topic   : nav_vel
  timeout : 0.1
  priority: 10
-
  name    : plane_reset # velocity for periodically base plane reset
  topic   : reset_vel
  timeout : 2.0
  priority: 50
-
  name    : keyboard # keyboard control
  topic   : key_vel
  timeout : 0.1
  priority: 100
